# Generated by Django 4.1.7 on 2023-02-26 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unspecified', 'UNSPECIFIED')], max_length=20)),
                ('dob', models.DateField()),
                ('regdate', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=True)),
                ('is_patient', models.BooleanField(default=False)),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unspecified', 'UNSPECIFIED')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=True)),
                ('employee_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unspecified', 'UNSPECIFIED')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('regdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('unspecified', 'UNSPECIFIED')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('occupation', models.CharField(max_length=100)),
                ('regdate', models.DateField(auto_now_add=True)),
                ('guardianname', models.CharField(max_length=100)),
                ('guardianphonenumber', models.CharField(max_length=15)),
                ('guardianrelation', models.CharField(choices=[('Brother', 'Brother'), ('Parent', 'Parent'), ('Spouse', 'Spouse'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
    ]
